bsd/dbt-arc-functions

macros/supermetrics_yahoo_dsp_paidmedia/sources/supermetrics_yahoo_dsp.yml
macros/supermetrics_yahoo_dsp_paidmedia/staging/stg_supermetrics_yahoo_dsp_paidmedia_campaigns.sql
macros/supermetrics_yahoo_dsp_paidmedia/staging/stg_supermetrics_yahoo_dsp_paidmedia_clicks_daily_rollup.sql
macros/supermetrics_yahoo_dsp_paidmedia/staging/stg_supermetrics_yahoo_dsp_paidmedia_impressions_daily_rollup.sql
macros/supermetrics_yahoo_dsp_paidmedia/staging/stg_supermetrics_yahoo_dsp_paidmedia_spends_daily_rollup.sql
utils/create_or_update_standard_models.py

Create or update standard models

---

utils/add_dependencies.py

This adds dependencies to sql files by continuously running dbt locally till no added dependencies are needed.

Make add_dependencies.py

---

macros/frakture_facebook_paidmedia/staging/stg_frakture_facebook_paidmedia_transactions_sourced_rollup.sql
macros/frakture_twitter_paidmedia/staging/stg_frakture_twitter_paidmedia_transactions_sourced_rollup.sql

It seems like moneys are coming through!

Try Frakture Attribution

---

macros/frakture_global_transactions/staging/stg_frakture_global_transactions.sql
macros/transactions/marts/mart_transactions_daily_rollup.sql
macros/transactions/staging/stg_transactions_unioned.sql

Creates macros for:
Frakture Global Transactions
Transactions Unioned Staging Table (just in case we have to get transactions from elsewhere)
Transactions Mart

Create Transaction Macros

---

utils/delete_schemas.py
utils/first_run_dbt_project_and_profiles_fixer.py
utils/main.py

Oftentimes it helps to delete existing dbt user schemas to start fresh with a new build. This script adds that functionality. Runs this by default in main.py.

Add delete schemas if exist functionality to utils

---

utils/clone_all_tables_and_views_in_schema.ipynb

Was taking over an hour to run on partitioned tables so made it asynchronous

allow to run async

---

.gitignore
utils/README.md
utils/clone_all_tables_and_views_in_schema.ipynb
utils/create_views_from_stitch_datasets.ipynb

Add a script to copy datasets from stitch

Add_stitch_copy

---

macros/combined_email_paidmedia/marts/mart_combined_email_paidmedia_daily_revenue_performance.sql
macros/email/marts/mart_email_performance_with_revenue.sql
macros/email/staging/stg_email_campaigns_unioned.sql
macros/frakture_global_message_email/staging/stg_frakture_global_message_email_campaigns.sql
macros/frakture_global_message_paidmedia/staging/stg_frakture_global_message_paidmedia_campaigns.sql
macros/frakture_global_transactions/staging/stg_frakture_global_transactions.sql
macros/paidmedia/marts/mart_paidmedia_daily_revenue_performance.sql
macros/transactions/marts/mart_transactions_daily_rollup.sql

See https://github.com/bsd/arc-campaigns-fairfight-dbt/pull/2 
https://github.com/bsd/dbt-arc-functions/issues/47

Fairfight add entity feature

---

macros/email/marts/mart_email_performance_with_revenue.sql
macros/email/staging/stg_email_actions_rollup_unioned.sql
macros/frakture_global_message_email/staging/stg_frakture_global_message_email_actions_rollup.sql

added actions to email reporting

---

macros/email/marts/mart_email_performance_with_revenue.sql
macros/frakture_global_message_email/staging/stg_frakture_global_message_email_campaigns.sql
macros/frakture_global_message_email/staging/stg_frakture_global_message_email_campaigns_rollup.sql

Fair Fight Branch since this is the data we are currently using for the bulk & triggered demo
-  [not needed] also re-run the `create_or_update_standard_models.py` for the client dbt project, replacing models and dependencies
fair fight was already in revision 2.6.1, so no update of models needed
@dmbluestate primary reviewer?

added campaign category field from message_set frakture source code

---

utils/Pipfile.lock
utils/first_run_dbt_project_and_profiles_fixer.py

ARC-842 get revision or branch

---

README.md
pull_request_template.md

this is a GitHub readme and pr format adjustment that adds steps related to adding dbt documentation for each PR

Adjust readme & pr format

---

macros/email/marts/mart_email_performance_with_revenue.sql
macros/email/staging/stg_email_complaints_rollup_unioned.sql
macros/frakture_global_message_email/staging/stg_frakture_global_message_email_complaints_rollup.sql
macros/mart_email.md

- [ X] If applicable, add documentation using the `schema.yml` macros documentation with embedded markdown docs (see `mart_email.md` for example) 
- [ X] Test branch on a development branch of an existing client (ideally the one that raised the bug). Do this by changing revision of the package to the branch name in `packages.yml` file in dbt State client below.
- [ X] Re-run `create_or_update_standard_models.py` for the client dbt project, replacing models and dependencies
- [ X] check in dbt that client package successfully runs `dbt deps`, `dbt compile`, and `dbt run`; screenshot this page
- <img width="1919" alt="Screen Shot 2022-09-22 at 12 02 09 PM" src="https://user-images.githubusercontent.com/109629735/191796378-d106ef6c-1ad9-4ff6-a716-743e3e43ea2e.png">
- [X ] query the resulting …

Add spam complaints to email reporting fields

---

macros/list_size/marts/mart_email_list_size_by_month_date.sql
macros/list_size/staging/stg_email_list_size_by_year_and_month.sql
macros/list_size/staging/stg_email_list_size_by_year_and_month_concat.sql
macros/mart_email_listsize.md
macros/schema.yml

- [c] If applicable, add documentation using the `schema.yml` macros documentation with embedded markdown docs (see `mart_email.md` for example) 
https://bluestate.atlassian.net/browse/ARC-959?atlOrigin=eyJpIjoiYTIyN2E4ZDM4MTZjNGM4OThiMTAyMThmMzQ5YTY1MWUiLCJwIjoiaiJ9

Create list size mart

---

macros/list_size/marts/mart_email_list_size_by_month_date.sql
macros/schema.yml

added one line to remove null in table

where concat date is not null

---

macros/schema.yml

Add complaints to arguments in the schema.yml file

---

.github/workflows/add_todos_as_issues.yml

try adding workflow

---

documentation/combined_email_paidmedia/marts/mart_combined_email_paidmedia_daily_revenue_performance.yml

try with 1 file first

---

macros/email_listhealth/staging/stg_email_listhealth_by_year_and_month_concat.sql
macros/email_listhealth/staging/stg_email_listhealth_with_prev_delivered.sql

- [not applicable] If applicable, add documentation using the `schema.yml` macros documentation with embedded markdown docs (see `mart_email.md` for example) 
mercy corps 
- [not applicable] Re-run `create_or_update_standard_models.py` for the client dbt project, replacing models and dependencies
https://bluestate.atlassian.net/browse/ARC-1019?atlOrigin=eyJpIjoiMzI3NzQ0NTQwNDhiNDFmNzllZjlkMDM4MWMzNzk3ZmEiLCJwIjoiaiJ9

patch - fix for previous delivered month

---

utils/create_or_update_standard_models.py

This now writes to a schema.yml file rather than a bunch of individual .yml files, so sorry about this error @Frydafly

Fix docs issue with create or update standard models

---

macros/transactions/marts/mart_transactions_hourly_rollup.sql

- [WIP] If applicable, add documentation using the `schema.yml` macros documentation with embedded markdown docs (see `mart_email.md` for example) 
Mercy Corps
https://bluestate.atlassian.net/browse/ARC-1099?atlOrigin=eyJpIjoiM2ZlNzIwN2I0YzlmNGQ5MTk0NjE1YjM4Y2JkN2RlMGMiLCJwIjoiaiJ9

create hourly transaction rollup

---

utils/create_or_update_standard_models.py
utils/first_run_dbt_project_and_profiles_fixer.py

just a helpful thing for posterity

Added docstring to our most commonly used utils scripts

---

utils/create_or_update_standard_models.py

- [v] If exists, link bug issue and jira tickets to PR
https://github.com/bsd/dbt-arc-functions/issues/135
https://bluestate.atlassian.net/jira/software/c/projects/ARC/boards/245?modal=detail&selectedIssue=ARC-1230&assignee=612ce3543249580071a2c9cb

Show sorted list in create_or_update_standard_models

---

utils/first_run_dbt_project_and_profiles_fixer.py

addresses https://github.com/bsd/dbt-arc-functions/issues/138

changes to first_run_dbt_project_fixer.py

---

pull_request_template.md

updated pull request template to reflect codegen package

---

utils/add_github_actions_workflows.py
utils/yml_files/dbt_run_on_trigger.yml

**prod workflow (on merge):**
**dev workflow (on PR and all pushes to that PR):**
https://bluestate.atlassian.net/browse/ARC-1250

ARC-1250-Add-a-differentiation-between-dev-and-prod-workflows-to-dbt_run_on_merge.yml

---

macros/README.md
utils/README.md
utils/create_or_update_standard_models.py

- [not applicable] If you've created a macro, make sure it is documented by running the notebook: `process_model_documentation_codegen_output.ipynb` util in this repo
- [not applicable] Test branch on a development branch of an existing client (ideally the one that raised the bug). Do this by changing revision of the package to the branch name in `packages.yml` file in dbt State client below.
- [not applicable ] If new macro files were created or updated, re-run `create_or_update_standard_models.py` for the client dbt project, replacing models and dependencies
- [not applicable ] check in dbt that client package successfully runs `dbt deps`, `dbt compile`, and `dbt run`; screenshot this page
- [not applicable ] query the resulting staging model in bigquery (or by previewing mart in dbt …

Add documentation about macros folders

---

documentation/frakture_actionkit_email/staging/stg_frakture_actionkit_email_actions_rollup.yml
documentation/frakture_actionkit_email/staging/stg_frakture_actionkit_email_bounces_rollup.yml
documentation/frakture_actionkit_email/staging/stg_frakture_actionkit_email_campaign_dates.yml
documentation/frakture_actionkit_email/staging/stg_frakture_actionkit_email_campaign_dates_rollup.yml
documentation/frakture_actionkit_email/staging/stg_frakture_actionkit_email_campaigns.yml
documentation/frakture_actionkit_email/staging/stg_frakture_actionkit_email_campaigns_rollup.yml
documentation/frakture_actionkit_email/staging/stg_frakture_actionkit_email_clicks_rollup.yml
documentation/frakture_actionkit_email/staging/stg_frakture_actionkit_email_complaints_rollup.yml
documentation/frakture_actionkit_email/staging/stg_frakture_actionkit_email_jobs.yml
documentation/frakture_actionkit_email/staging/stg_frakture_actionkit_email_opens_rollup.yml
documentation/frakture_actionkit_email/staging/stg_frakture_actionkit_email_recipients_rollup.yml
documentation/frakture_actionkit_email/staging/stg_frakture_actionkit_email_summary_unioned.yml
documentation/frakture_actionkit_email/staging/stg_frakture_actionkit_email_transactions_sourced_rollup.yml
documentation/frakture_actionkit_email/staging/stg_frakture_actionkit_email_unsubscribes_rollup.yml
documentation/frakture_actionkit_email/staging/stg_frakture_actionkit_transactions_summary_unioned.yml

https://bluestate.atlassian.net/browse/ARC-1288

ARC-1288 add filler for frakture_actionkit_email

---

documentation/frakture_actionkit_email/staging/stg_frakture_actionkit_email_jobs.yml

https://bluestate.atlassian.net/browse/ARC-1272

Arc 1272 write documentation for stg frakture actionkit email jobs

---

documentation/frakture_everyaction_email/staging/stg_frakture_everyaction_email_bounces_rollup.yml
documentation/frakture_everyaction_email/staging/stg_frakture_everyaction_email_clicks_rollup.yml
documentation/frakture_everyaction_email/staging/stg_frakture_everyaction_email_jobs.yml
documentation/frakture_everyaction_email/staging/stg_frakture_everyaction_email_message_unioned.yml
documentation/frakture_everyaction_email/staging/stg_frakture_everyaction_email_opens_rollup.yml
documentation/frakture_everyaction_email/staging/stg_frakture_everyaction_email_recipients_rollup.yml
documentation/frakture_everyaction_email/staging/stg_frakture_everyaction_email_summary_unioned.yml
documentation/frakture_everyaction_email/staging/stg_frakture_everyaction_email_transactions_sourced_rollup.yml
documentation/frakture_everyaction_email/staging/stg_frakture_everyaction_email_unsubscribes_rollup.yml

https://bluestate.atlassian.net/browse/ARC-1289

ARC-1289 add frakture_everyaction_email filler

---

utils/first_run_dbt_project_and_profiles_fixer.py

no change in functionality expected

honestly just added a bunch of comments and todos 

---

utils/create_or_update_standard_models.py

https://bluestate.atlassian.net/browse/ARC-1312

ARC-1312 add README creator

---

documentation/frakture_global_message_email/staging/stg_frakture_global_message_email_summary.yml

https://bluestate.atlassian.net/browse/ARC-1068

Arc 1068 write documentation for stg frakture global message email summary

---

sources/frakture_global_message_email.yml

Jira issue:
https://bluestate.atlassian.net/jira/software/c/projects/ARC/boards/245?modal=detail&selectedIssue=ARC-1362&search=frakture

Add blank columns for Frakture Global Message Email

---

sources/frakture_global_message_email.yml

JIRA ticket:
https://bluestate.atlassian.net/browse/ARC-1361

ARC-1361-write-documentation-for-frakture-global-message-email-global-message-summary-by-date

---

utils/add_dependencies.py

- Link to Jira ticket:
https://bluestate.atlassian.net/browse/ARC-1293
- Screenshot of it working:

ARC-1293-to-add_dependencies-for-no-version-check

---

utils/first_run_dbt_project_and_profiles_fixer.py

https://bluestate.atlassian.net/browse/ARC-1344

ARC-1344 active branch or most recent revision

---

README.md
pull_request_template.md

https://bluestate.atlassian.net/browse/ARC-1495
https://bluestate.atlassian.net/browse/ARC-1496
Just makes sure that every macro has a doc associated with it in the documentation folder with the same folder structure, i.e.:
is the doc for
` …

ARC-1495 Update pull request template

---

macros/utils/get_fiscal_date_part.md
macros/utils/get_fiscal_date_part.sql
macros/utils/get_fiscal_date_part.yml
utils/first_run_dbt_project_and_profiles_fixer.py

https://bluestate.atlassian.net/browse/ARC-1494
Tested on Mercycorps:
https://github.com/bsd/arc-mercycorps-dbt/pull/29
No new model macros created
Successful dbt run after deps and compile
Query: 
```sql
SELECT * 
FROM `bsd-mercycorps.dbt_tryan_marts.mart_combined_email_paidmedia_with_financial_date` 
LIMIT 1000
```
You can see how the fiscal year changes 7/1
Run:
```console
cd utils
pipenv shell
python first_run_dbt_project_and_profiles_fixer.py
```
against a blank project to see the new add fiscal year prompt.
If any of them detect syntax problems, they will error. They will automatically …

Arc 1494 audience tech planning create framework in dbt arc functions to flag fiscal year

---

.github/workflows/check_for_properly_formatted_docs.yml
.github/workflows/python_black.yml
.github/workflows/sqlfmt_linter.yml
.github/workflows/yaml_linter.yml
utils/check_docs_correct.py

Fix Derrick's problems with linter.

ARC-1431-fix-linter

---

macros/README.md

https://bluestate.atlassian.net/browse/ARC-1338

ARC-1338 add customizable macro explainer

---

documentation/stitch_sfmc_audience_transaction/staging/stg_stitch_sfmc_customizable_audience_transaction_jobs_append.yml

ARC-1548 indent column list

---

macros/stitch_sfmc_email/staging/stg_stitch_sfmc_customized_email_campaigns.sql
macros/stitch_sfmc_email/staging/stg_stitch_sfmc_email_jobs.sql

uusa
- [NA ] If new macro files were created or updated, re-run `create_or_update_standard_models.py` for the client dbt project, replacing models and dependencies
`documentation/combined_email_paidmedia/marts/mart_combined_email_paidmedia_dail …

ARC-1582-changing campaign to campaign_category, allowing it to pull into mart

---

documentation/stitch_sfmc_audience_transaction/staging/stg_stitch_sfmc_audience_transactions_enriched_rollup_join_person_and_transaction.yml
macros/stitch_sfmc_audience_transaction/staging/stg_stitch_sfmc_audience_transactions_enriched_rollup_join_person_and_transaction.sql

https://bluestate.atlassian.net/browse/ARC-1511
https://github.com/bsd/arc-uusa-dbt/pull/29

ARC-1511 add audience person transaction macro

---

macros/audience_budget/staging/stg_audience_budget_by_day_enriched.sql
macros/stitch_sfmc_arc/staging/stg_stitch_sfmc_arc_audience_union_transaction_joined_enriched.sql
macros/stitch_sfmc_arc/staging/stg_stitch_sfmc_arc_audience_unioned.sql
macros/stitch_sfmc_arc/staging/stg_stitch_sfmc_audience_transaction_calculated_alldates.sql
macros/stitch_sfmc_audience_transaction/marts/mart_cashflow_actuals_and_budget.sql
macros/stitch_sfmc_audience_transaction/marts/mart_cashflow_actuals_and_budget_1x_revenue.sql
macros/stitch_sfmc_deliverability/staging/stg_stitch_sfmc_deliverability_bounces_daily_rollup.sql
macros/stitch_sfmc_deliverability/staging/stg_stitch_sfmc_deliverability_clicks_daily_rollup.sql
macros/stitch_sfmc_deliverability/staging/stg_stitch_sfmc_deliverability_opens_daily_rollup.sql
macros/stitch_sfmc_deliverability/staging/stg_stitch_sfmc_deliverability_unsubscribes_daily_rollup.sql
macros/stitch_sfmc_email/staging/stg_src_stitch_email_bounce.sql
macros/stitch_sfmc_email/staging/stg_src_stitch_email_sent.sql
macros/stitch_sfmc_email/staging/stg_stitch_sfmc_email_bounces_rollup.sql
macros/stitch_sfmc_email/staging/stg_stitch_sfmc_email_clicks_rollup.sql
macros/stitch_sfmc_email/staging/stg_stitch_sfmc_email_complaints_rollup.sql
macros/stitch_sfmc_email/staging/stg_stitch_sfmc_email_opens_rollup.sql
macros/stitch_sfmc_email/staging/stg_stitch_sfmc_email_recipients_rollup.sql
macros/stitch_sfmc_email/staging/stg_stitch_sfmc_email_unsubscribes_rollup.sql

- [NA] Make sure the Macro is documented by running the notebook: `create_docs.ipynb` util in this repo. From there, you'll have to either fill in descriptions by hand OR use our `fill_in_descriptions_using_openai.ipynb` to fill in descriptions using OpenAI's ChatGPT. Always make sure to check over ChatGPT's column descriptions, as they're likely not perfect.
- [NA] If new macro files were created or updated, re-run `create_or_update_standard_models.py` for the client dbt project, replacing models and dependencies
If any of them detect syntax problems, they will error. They will automatically …

Arc 1597 email reporting bug open rate is too high in mart email performance with revenue

---

documentation/stitch_sfmc_arc/staging/stg_stitch_sfmc_arc_audience_union_transaction_joined_enriched.yml
documentation/stitch_sfmc_arc/staging/stg_stitch_sfmc_arc_donor_loyalty_by_fiscal_year.yml
documentation/stitch_sfmc_arc/staging/stg_stitch_sfmc_arc_donor_loyalty_fiscal_year_count.yml
documentation/stitch_sfmc_arc/staging/stg_stitch_sfmc_arc_donor_loyalty_validation.yml
macros/stitch_sfmc_arc/staging/stg_stitch_sfmc_arc_audience_union_transaction_joined.sql
macros/stitch_sfmc_arc/staging/stg_stitch_sfmc_arc_audience_union_transaction_joined_enriched.sql
macros/stitch_sfmc_arc/staging/stg_stitch_sfmc_arc_donor_loyalty_by_fiscal_year.sql
macros/stitch_sfmc_arc/staging/stg_stitch_sfmc_arc_donor_loyalty_fiscal_year_count.sql
macros/stitch_sfmc_arc/staging/stg_stitch_sfmc_arc_donor_loyalty_validation.sql
macros/stitch_sfmc_arc/staging/stg_stitch_sfmc_src_donor_loyalty_validation.sql

ARC- UUSA
https://github.com/bsd/arc-uusa-dbt/tree/ARC-1560-Audience-Tech-Planning-Donor-Loyalty-by-Year-and-Person-Core-Table
is the …

Arc 1560 audience tech planning donor loyalty by year and person core table

---

documentation/arc_revenue/marts/mart_arc_revenue_1x_actuals_by_day.yml
documentation/arc_revenue/marts/mart_arc_revenue_recur_actuals_by_day.yml
macros/arc_revenue/marts/mart_arc_revenue_1x_actuals_by_day.sql
macros/arc_revenue/marts/mart_arc_revenue_recur_actuals_by_day.sql

https://bluestate.atlassian.net/browse/ARC-1615
https://github.com/bsd/arc-uusa-dbt/pull/40

Arc 1615 audience reporting bug add field or something in models with string ranges to ensure sorting in looker

---

macros/stitch_sfmc_audience_transaction/staging/stg_stitch_sfmc_audience_transactions_enriched_rollup_join_person_and_transaction.sql

Right now there's a row for every day, every person. What we'd like is one row per transaction.
uusa link:
https://github.com/bsd/arc-uusa-dbt/pull/42

ARC-1621 from transactions first

---

macros/audience_budget_with_audience_transaction/marts/mart_audience_budget_with_audience_transaction.sql
macros/audience_budget_with_audience_transaction/marts/mart_audience_budget_with_audience_transaction_recur.sql
macros/stitch_sfmc_audience_transaction/staging/stg_stitch_sfmc_audience_transaction_onetime_donor_counts_actuals_rollup.sql
macros/stitch_sfmc_audience_transaction/staging/stg_stitch_sfmc_audience_transaction_recur_donor_counts_combined.sql
macros/stitch_sfmc_audience_transaction/staging/stg_stitch_sfmc_audience_transaction_recur_donor_counts_daily.sql
macros/stitch_sfmc_audience_transaction/staging/stg_stitch_sfmc_audience_transaction_recur_donor_counts_monthly.sql
macros/stitch_sfmc_audience_transaction/staging/stg_stitch_sfmc_audience_transaction_recur_donor_counts_yearly.sql

Add reinstated to marts
https://bluestate.atlassian.net/browse/ARC-1622
https://github.com/bsd/arc-uusa-dbt/pull/44

ARC-1622-audience-reporting-bug-add-total-reinstated-field-to-mart-audience-budget-with-transaction

---

macros/audience_budget/staging/stg_adhoc_google_spreadsheets_audience_monthly_budget.sql
macros/audience_budget/staging/stg_audience_budget_by_day_enriched.sql
macros/frakture_global_transactions/staging/stg_frakture_global_transactions.sql
macros/paidmedia_goals/staging/stg_adhoc_google_spreadsheets_paidmedia_monthly_goals.sql
macros/stitch_sfmc_arc/staging/stg_stitch_sfmc_arc_audience_by_date_day.sql
macros/stitch_sfmc_arc/staging/stg_stitch_sfmc_arc_audience_unioned.sql
macros/stitch_sfmc_arc/staging/stg_stitch_sfmc_arc_calculated_audience_by_date_day.sql
macros/stitch_sfmc_audience_transaction/staging/stg_stitch_sfmc_audience_transaction_jobs_append.sql
macros/stitch_sfmc_audience_transaction/staging/stg_stitch_sfmc_parameterized_audience_transactions_enriched.sql

Make platform, join_source and channel initcapped.
Make audiences the same across tables.
https://bluestate.atlassian.net/browse/ARC-1620
https://github.com/bsd/arc-uusa-dbt/pull/43

ARC-1620 remove coercion to our naming schema

---

macros/arc_revenue/marts/mart_arc_revenue_recur_actuals_by_day.sql
macros/stitch_sfmc_audience_transaction/staging/stg_stitch_sfmc_audience_transaction_first_gift.sql
macros/stitch_sfmc_audience_transaction/staging/stg_stitch_sfmc_audience_transactions_enriched_rollup_join_person_and_transaction.sql

add a different donation size string for recurs, also different sort
https://bluestate.atlassian.net/browse/ARC-1625
https://github.com/bsd/arc-uusa-dbt/pull/45

ARC-1625 add recur string and recur sort

---

documentation/arc_revenue/marts/mart_arc_revenue_recur_donor_counts_by_gift_size.yml
documentation/stitch_sfmc_arc/staging/stg_stitch_sfmc_arc_recur_donor_counts_by_gift_size_daily.yml
documentation/stitch_sfmc_arc/staging/stg_stitch_sfmc_arc_recur_donor_counts_by_gift_size_monthly.yml
documentation/stitch_sfmc_arc/staging/stg_stitch_sfmc_arc_recur_donor_counts_by_gift_size_yearly.yml
macros/arc_revenue/marts/mart_arc_revenue_recur_donor_counts_by_gift_size.sql
macros/stitch_sfmc_arc/staging/stg_stitch_sfmc_arc_recur_donor_counts_by_gift_size_daily.sql
macros/stitch_sfmc_arc/staging/stg_stitch_sfmc_arc_recur_donor_counts_by_gift_size_monthly.sql
macros/stitch_sfmc_arc/staging/stg_stitch_sfmc_arc_recur_donor_counts_by_gift_size_yearly.sql
macros/stitch_sfmc_audience_transaction/staging/stg_stitch_sfmc_audience_transaction_onetime_donor_counts_actuals_rollup.sql
macros/stitch_sfmc_audience_transaction/staging/stg_stitch_sfmc_audience_transaction_recur_donor_counts_daily.sql
macros/stitch_sfmc_audience_transaction/staging/stg_stitch_sfmc_audience_transaction_recur_donor_counts_monthly.sql
macros/stitch_sfmc_audience_transaction/staging/stg_stitch_sfmc_audience_transaction_recur_donor_counts_yearly.sql

https://bluestate.atlassian.net/browse/ARC-1643
https://github.com/bsd/arc-uusa-dbt/pull/56

Arc 1643 all donors being counted as new

---

macros/audience_budget/staging/stg_audience_budget_by_day_enriched.sql
macros/stitch_sfmc_audience_transaction/marts/mart_cashflow_actuals_and_budget.sql
macros/stitch_sfmc_audience_transaction/marts/mart_cashflow_actuals_and_budget_1x_revenue.sql

Arc 1672 audience reporting bug move all recurring revenue into recurring channel

---

sources/adhoc_google_spreadsheets_paidmedia_goals.yml
sources/adhoc_google_spreadsheets_paidmedia_pacing.yml
sources/audience_budget.yml
sources/frakture_global_message_email.yml
sources/frakture_global_message_paidmedia.yml
sources/frakture_global_transactions.yml
sources/src_uusa_bbcrm_historical.yml
sources/stitch_sfmc_arc.yml
sources/stitch_sfmc_bbcrm.yml
sources/stitch_sfmc_bbcrm_transactions.yml
sources/stitch_sfmc_email.yml
sources/stitch_sfmc_fundraiseup_transactions.yml

https://bluestate.atlassian.net/browse/ARC-1241?atlOrigin=eyJpIjoiMDBmODhlODcwNTY4NDgyM2I2ZGVhZDYwMzY2MjkxZTMiLCJwIjoiaiJ9 
- [n/a] Make sure the Macro is documented by running the notebook: `create_docs.ipynb` util in this repo. From there, you'll have to either fill in descriptions by hand OR use our `fill_in_descriptions_using_openai.ipynb` to fill in descriptions using OpenAI's ChatGPT. Always make sure to check over ChatGPT's column descriptions, as they're likely not perfect.
https://github.com/bsd/arc-uusa-dbt/pull/63 
- [n/a] If new macro files were created or updated, re-run `create_or_update_standard_models.py` for the client dbt project, replacing models and dependencies
`dbt test` result
- [n/a] query the resulting staging model in bigquery (or by previewing mart in dbt cloud, …

Arc 1241 write source level tests prioritize spreadsheet frakture then stitch

---

macros/stitch_sfmc_bbcrm_transactions/staging/stg_stitch_sfmc_bbcrm_transactions.sql
macros/stitch_sfmc_fundraiseup_transactions/staging/stg_stitch_sfmc_fundraiseup_filtered_recent_transactions.sql

ARC-1695-Audience-Reporting-BUG-Redefine-Recurring-logic-to-match-UUSA-client-preferences

---

macros/stitch_sfmc_audience_transaction/staging/stg_stitch_sfmc_audience_transactions_enriched_rollup_join_person_and_transaction.sql

https://bluestate.atlassian.net/browse/ARC-1667
https://github.com/bsd/arc-uusa-dbt/pull/65
https://cloud.getdbt.com/deploy/1713/projects/207950/runs/213927896

ARC-1667 add clustering to config

---

macros/stitch_sfmc_audience_transaction/staging/stg_stitch_sfmc_audience_transactions_enriched_rollup_join_person_and_transaction.sql
macros/utils/util_stg_stitch_sfmc_audience_transaction_frequency_donor_counts_interval.sql

use best_guess_inbound_channel instead of join_source as platform
Builds correctly:
https://github.com/bsd/arc-uusa-dbt/pull/73

ARC-1713 use best_guess_inbound_channel

---

macros/arc_revenue/marts/mart_arc_revenue_1x_actuals_by_day.sql
macros/arc_revenue/marts/mart_arc_revenue_recur_actuals_by_day.sql

…monthly donor audience.
https://bluestate.atlassian.net/browse/ARC-1699?atlOrigin=eyJpIjoiZGM1MjI5YTExYWFiNDMxMmE0MGVhMmVlY2VmMTJmNDYiLCJwIjoiaiJ9
https://bluestate.atlassian.net/browse/ARC-1728?atlOrigin=eyJpIjoiZGJkMjJmMjQ4YjgwNGU4OGFhZTdhNjE1OTdhM2IyN2IiLCJwIjoiaiJ9
Makes sure that every macro has a doc associated with it in the documentation folder with the …

ARC-1728-mart_arc_revenue_recur_actuals_by_day-channel-values-incorrect

---

macros/stitch_sfmc_audience_transaction/staging/stg_stitch_sfmc_audience_transactions_summary_unioned.sql

ARC-1755-Filter-transactions-to-old-show-digital-transactions

---

macros/utils/util_mart_audience_budget_with_audience_transaction.sql

https://github.com/bsd/arc-uusa-dbt/pull/88
is the doc for
`       macros/combined_email_paidmedia/marts/mart_combined_email_paidmedia_da …

HOT-FIX: add missing field to mart - new_to_fy_{recur_onetime}donor_counts

---

documentation/stitch_google_grant_paidmedia/staging/stg_stitch_google_grant_paidmedia_campaigns.yml
documentation/stitch_google_grant_paidmedia/staging/stg_stitch_google_grant_paidmedia_clicks_daily_rollup.yml
documentation/stitch_google_grant_paidmedia/staging/stg_stitch_google_grant_paidmedia_impressions_daily_rollup.yml
documentation/stitch_google_grant_paidmedia/staging/stg_stitch_google_grant_paidmedia_spends_daily_rollup.yml
documentation/stitch_google_grant_paidmedia/staging/stg_stitch_google_grant_paidmedia_subscribes_daily_rollup.yml
documentation/stitch_google_grant_paidmedia/staging/stg_stitch_google_grant_paidmedia_transactions_sourced_rollup.yml
macros/stitch_google_grant_paidmedia/staging/stg_stitch_google_grant_paidmedia_campaigns.sql
macros/stitch_google_grant_paidmedia/staging/stg_stitch_google_grant_paidmedia_clicks_daily_rollup.sql
macros/stitch_google_grant_paidmedia/staging/stg_stitch_google_grant_paidmedia_impressions_daily_rollup.sql
macros/stitch_google_grant_paidmedia/staging/stg_stitch_google_grant_paidmedia_spends_daily_rollup.sql
macros/stitch_google_grant_paidmedia/staging/stg_stitch_google_grant_paidmedia_subscribes_daily_rollup.sql
macros/stitch_google_grant_paidmedia/staging/stg_stitch_google_grant_paidmedia_transactions_sourced_rollup.sql
sources/stitch_google_grant_paidmedia.yml
sources/stitch_googleads_paidmedia.yml

Arc 1759 check to ensure that youtube data will flow through google ads conection

---

macros/stitch_google_grant_paidmedia/staging/stg_stitch_google_grant_paidmedia_spends_daily_rollup.sql

HOTFIX_ARC-1759-Check-to-ensure-that-youtube-data-will-flow-through-google-ads-conection

---

documentation/audience_budget_with_audience_transaction/marts/mart_audience_budget_with_audience_transaction.yml
documentation/audience_budget_with_audience_transaction/marts/mart_audience_budget_with_audience_transaction_recur.yml
macros/stitch_sfmc_audience_transaction/staging/stg_stitch_sfmc_audience_transactions_enriched_rollup_join_person_and_transaction.sql
macros/utils/util_stg_audience_budget_frequency_donor_counts_interval_type.sql
macros/utils/util_stg_audience_frequency_donor_counts_interval_rollup.sql

Arc 1756 live donor counts 1x and recur on day of cumulative count goes down

---

documentation/audience_budget_with_audience_transaction/marts/mart_audience_budget_with_audience_transaction.yml
documentation/audience_budget_with_audience_transaction/marts/mart_audience_budget_with_audience_transaction_recur.yml
macros/utils/util_mart_audience_budget_with_audience_transaction.sql
macros/utils/util_stg_audience_budget_frequency_donor_counts_interval_type.sql
macros/utils/util_stg_audience_transaction_frequency_donor_counts_interval_rollup.sql
macros/utils/util_stg_stitch_sfmc_audience_transaction_frequency_donor_counts_interval.sql
tests/generic/test_cumulative_column_values.sql

hotfifx - arc-1756

---

documentation/audience_budget_with_audience_transaction/marts/mart_audience_budget_with_audience_transaction.yml
documentation/audience_budget_with_audience_transaction/marts/mart_audience_budget_with_audience_transaction_recur.yml
macros/stitch_sfmc_audience_transaction/marts/mart_audience_recur_retention.sql
tests/audience/assert_rt00_is_equal_to_cohort.sql

https://github.com/bsd/arc-uusa-dbt/compare/ARC-1776-Retention-rate-at-RT00-is-under-100?expand=1 
is the doc for
` …

Arc 1776 retention rate at rt00 is under 100

---

tests/generic/has_same_distinct_values_as.sql

hotfix: move one test to warn and create bug ticket for it, instead of failure causing data issues

---

macros/stitch_sfmc_bbcrm_transactions/staging/stg_src_stitch_sfmc_bbcrm_transaction.sql

HOTFIX: try if target name is dev

---

macros/stitch_google_grant_paidmedia/staging/stg_stitch_google_grant_paidmedia_campaigns.sql
macros/stitch_google_grant_paidmedia/staging/stg_stitch_google_grant_paidmedia_clicks_daily_rollup.sql
macros/stitch_google_grant_paidmedia/staging/stg_stitch_google_grant_paidmedia_impressions_daily_rollup.sql
macros/stitch_google_grant_paidmedia/staging/stg_stitch_google_grant_paidmedia_spends_daily_rollup.sql
macros/stitch_google_grant_paidmedia/staging/stg_stitch_google_grant_paidmedia_subscribes_daily_rollup.sql
macros/stitch_google_grant_paidmedia/staging/stg_stitch_google_grant_paidmedia_transactions_sourced_rollup.sql
macros/stitch_googleads_paidmedia/staging/stg_stitch_google_paidmedia_campaigns.sql
macros/stitch_googleads_paidmedia/staging/stg_stitch_google_paidmedia_clicks_daily_rollup.sql
macros/stitch_googleads_paidmedia/staging/stg_stitch_google_paidmedia_impressions_daily_rollup.sql
macros/stitch_googleads_paidmedia/staging/stg_stitch_google_paidmedia_spends_daily_rollup.sql
macros/stitch_googleads_paidmedia/staging/stg_stitch_google_paidmedia_subscribes_daily_rollup.sql
macros/stitch_googleads_paidmedia/staging/stg_stitch_google_paidmedia_transactions_sourced_rollup.sql

ARC-1924-Missing-Google-Search-ads

---

macros/ga4_google_analytics_web/staging/stg_ga4_web_daily_purchases_rollup.sql
macros/ga4_google_analytics_web/staging/stg_ga4_web_daily_unique_users_rollup.sql

Arc 1893 nyccfb dashboard outage dbt run failures since oct 25 2023
